"""Human-readable definitions for generated factor artifacts."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class FactorMetadata:
    """Definition, defaults, source fields, and interpretation for one factor."""

    formula: str
    default_params: dict[str, Any]
    required_fields: dict[str, tuple[str, ...]]
    economic_meaning: str


FACTOR_METADATA: dict[str, FactorMetadata] = {
    "momentum": FactorMetadata(
        "close_t / close_{t-lookback_days} - 1",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures N-day price trend (lookback_days configurable). Positive values indicate recent gains.",
    ),
    "short_term_reversal": FactorMetadata(
        "-(close_t / close_{t-5} - 1)",
        {"lookback_days": 5},
        {"kline": ("close",)},
        "Captures short-horizon mean reversion after recent price moves.",
    ),
    "rsi": FactorMetadata(
        "100 - 100 / (1 + mean(gain,lookback_days) / mean(loss,lookback_days))",
        {"lookback_days": 14},
        {"kline": ("close",)},
        "Measures relative recent buying and selling pressure. Higher values indicate stronger upward moves.",
    ),
    "momentum_acceleration": FactorMetadata(
        "return_20 - return_5",
        {"long_window_days": 20, "short_window_days": 5},
        {"kline": ("close",)},
        "Measures whether longer-horizon momentum is strengthening relative to the short horizon.",
    ),
    "breakout_distance": FactorMetadata(
        "close_t / max(close over lookback_days) - 1",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures proximity to the trailing high. Values near zero indicate a local breakout state.",
    ),
    "realized_vol": FactorMetadata(
        "std(return, lookback_days) * sqrt(365)",
        {"lookback_days": 20, "annualization": 365},
        {"kline": ("close",)},
        "Measures recent realized volatility and the current level of price uncertainty.",
    ),
    "high_low_range": FactorMetadata(
        "mean((high-low)/close over lookback_days)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Uses average intrabar range as a simple volatility and liquidity-risk proxy.",
    ),
    "downside_vol": FactorMetadata(
        "sqrt(mean(min(return,0)^2,20)) * sqrt(365)",
        {"lookback_days": 20, "annualization": 365},
        {"kline": ("close",)},
        "Measures downside-only realized volatility rather than symmetric price variation.",
    ),
    "parkinson_vol": FactorMetadata(
        "sqrt(mean(log(high/low)^2,20)/(4*ln(2))) * sqrt(365)",
        {"lookback_days": 20, "annualization": 365},
        {"kline": ("high", "low")},
        "Uses the high-low range to estimate volatility with more intrabar information.",
    ),
    "volatility_of_volatility": FactorMetadata(
        "std(std(return,20),60)",
        {"vol_window_days": 20, "window_days": 60},
        {"kline": ("close",)},
        "Measures instability in realized volatility, which can indicate regime change.",
    ),
    "volume_ratio": FactorMetadata(
        "volume_t / mean(volume,20)",
        {"lookback_days": 20},
        {"kline": ("volume",)},
        "Measures whether current trading activity is elevated relative to recent history.",
    ),
    "turnover": FactorMetadata(
        "mean(volume/close,20)",
        {"lookback_days": 20},
        {"kline": ("volume", "close")},
        "Approximates recent trading activity normalized by price.",
    ),
    "dollar_volume": FactorMetadata(
        "mean(close*volume,20)",
        {"lookback_days": 20},
        {"kline": ("close", "volume")},
        "Measures average traded notional and is a direct liquidity proxy.",
    ),
    "volume_price_pressure": FactorMetadata(
        "mean(((close-open)/(high-low))*volume,20) / mean(volume,20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close", "volume")},
        "Uses signed intrabar price movement weighted by volume to proxy directional pressure.",
    ),
    "amihud_illiquidity": FactorMetadata(
        "mean(abs(return)/(close*volume),20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures price movement per unit of traded-notional proxy; higher values imply lower liquidity.",
    ),
    "close_location": FactorMetadata(
        "mean((close-low)/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Measures where the close falls within the intrabar range, a proxy for directional pressure.",
    ),
    "kline_order_imbalance": FactorMetadata(
        "mean(((2*close-high-low)/(high-low))*volume,20) / mean(volume,20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close", "volume")},
        "Uses close location and volume to proxy order-flow imbalance when trade data is unavailable.",
    ),
    "wick_imbalance": FactorMetadata(
        "mean((upper_wick-lower_wick)/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close")},
        "Measures asymmetric intrabar rejection of high versus low prices.",
    ),
    "intrabar_reversal": FactorMetadata(
        "mean((close-open)/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close")},
        "Measures signed candle-body share of the bar range as a directional microstructure proxy.",
    ),
    "funding_rate_annualized": FactorMetadata(
        "funding_rate_t * periods_per_year * 100",
        {"funding_interval_hours": 8, "periods_per_year": 1095},
        {"funding_rate": ("funding_rate",)},
        "Measures the annualized cost of perpetual leverage. Positive values imply longs pay shorts.",
    ),
    "funding_rate_zscore": FactorMetadata(
        "(funding_rate_t-mean(funding_rate,30))/(std(funding_rate,30)+epsilon)",
        {"lookback_days": 30, "epsilon": 1e-12},
        {"funding_rate": ("funding_rate",)},
        "Measures whether funding is unusually high or low relative to its recent history.",
    ),
    "oi_change_ratio": FactorMetadata(
        "open_interest_t / open_interest_{t-60} - 1",
        {"lookback_days": 60},
        {"open_interest": ("open_interest",)},
        "Measures changes in leveraged positioning and participation.",
    ),
    "oi_price_divergence": FactorMetadata(
        "return(open_interest,20) - return(close,20)",
        {"lookback_days": 20},
        {"kline": ("close",), "open_interest": ("open_interest",)},
        "Measures divergence between positioning growth and price movement.",
    ),
    "basis_latest": FactorMetadata(
        "basis_pct_t",
        {},
        {"basis": ("basis_pct",)},
        "Measures perpetual price premium or discount relative to spot.",
    ),
    "binance_mvrv_proxy": FactorMetadata(
        "close_t / VWAP(close, quote_volume, 365d)",
        {"lookback_days": 365},
        {"kline": ("close", "volume", "quote_volume")},
        "Measures price relative to a trailing Binance volume-weighted cost-basis proxy.",
    ),
    "binance_realized_price_proxy": FactorMetadata(
        "VWAP(close, quote_volume, 365d)",
        {"lookback_days": 365},
        {"kline": ("close", "volume", "quote_volume")},
        "Estimates a trailing Binance volume-weighted realized-price proxy.",
    ),
    "binance_mvrv_proxy_change": FactorMetadata(
        "mvrv_proxy_t / mvrv_proxy_{t-30d} - 1",
        {"lookback_days": 365, "change_days": 30},
        {"kline": ("close", "volume", "quote_volume")},
        "Measures the configurable-horizon change in the Binance MVRV proxy.",
    ),
    "binance_mvrv_proxy_zscore": FactorMetadata(
        "(mvrv_proxy - mean(mvrv_proxy, 730d)) / std(mvrv_proxy, 730d)",
        {"lookback_days": 365, "zscore_days": 730},
        {"kline": ("close", "volume", "quote_volume")},
        "Measures how unusual the Binance MVRV proxy is relative to its trailing history.",
    ),
    "basis_zscore": FactorMetadata(
        "(basis_pct_t-mean(basis_pct,30))/(std(basis_pct,30)+epsilon)",
        {"lookback_days": 30, "epsilon": 1e-12},
        {"basis": ("basis_pct",)},
        "Measures whether the spot-perpetual basis is unusual relative to recent history.",
    ),
    "crypto_gap_risk": FactorMetadata(
        "mean(abs(open_t / close_{t-1} - 1),20)",
        {"lookback_days": 20},
        {"kline": ("open", "close")},
        "Measures abrupt bar-to-bar repricing risk in the continuously traded crypto market.",
    ),
    "crypto_return_volume_corr": FactorMetadata(
        "corr(return, delta(log(volume)),20)",
        {"lookback_days": 20},
        {"kline": ("close", "volume")},
        "Measures whether price moves and changes in trading activity reinforce each other.",
    ),
    "crypto_tail_risk": FactorMetadata(
        "quantile(abs(return),0.95,60)",
        {"lookback_days": 60, "quantile": 0.95},
        {"kline": ("close",)},
        "Measures the recent upper tail of absolute crypto returns.",
    ),
    "crypto_volume_volatility": FactorMetadata(
        "std(delta(log(volume)),20)",
        {"lookback_days": 20},
        {"kline": ("volume",)},
        "Measures instability in trading activity, a crypto-specific regime indicator.",
    ),
    "crypto_weekend_activity_ratio": FactorMetadata(
        "mean(weekend_volume,20) / mean(volume,20)",
        {"lookback_days": 20},
        {"kline": ("timestamp", "volume")},
        "Measures the share of recent activity occurring on weekends in the 24/7 market.",
    ),
    "momentum_skip": FactorMetadata(
        "close_{t-5} / close_{t-25} - 1",
        {"skip_days": 5, "lookback_days": 20},
        {"kline": ("close",)},
        "Measures medium-term momentum while excluding the most recent five observations.",
    ),
    "momentum_consistency": FactorMetadata(
        "mean(up_return,20) - mean(down_return,20)",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures whether positive or negative return observations dominate recently.",
    ),
    "trend_strength": FactorMetadata(
        "abs(sum(return,20)) / (sum(abs(return),20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures directional efficiency of the recent price path.",
    ),
    "moving_average_distance": FactorMetadata(
        "close_t / mean(close,20) - 1",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures the current close's distance from its short-term trend baseline.",
    ),
    "moving_average_crossover": FactorMetadata(
        "mean(close,10) / mean(close,30) - 1",
        {"short_window_days": 10, "long_window_days": 30},
        {"kline": ("close",)},
        "Measures short moving-average trend relative to a longer moving average.",
    ),
    "donchian_position": FactorMetadata(
        "(close_t - min(close,20)) / (max(close,20) - min(close,20))",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures the close's position inside the recent price channel.",
    ),
    "atr_ratio": FactorMetadata(
        "mean(true_range,14) / close",
        {"lookback_days": 14},
        {"kline": ("high", "low", "close")},
        "Measures average true range normalized by price.",
    ),
    "true_range_ratio": FactorMetadata(
        "mean(true_range / previous_close,20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Measures recent total bar-to-bar range risk relative to price.",
    ),
    "garman_klass_vol": FactorMetadata(
        "sqrt(mean(0.5*log(high/low)^2-(2*ln(2)-1)*log(close/open)^2,20))*sqrt(365)",
        {"lookback_days": 20, "annualization": 365},
        {"kline": ("open", "high", "low", "close")},
        "Estimates volatility using open, high, low, and close information.",
    ),
    "rogers_satchell_vol": FactorMetadata(
        "sqrt(mean(log(high/close)*log(high/open)+log(low/close)*log(low/open),20))*sqrt(365)",
        {"lookback_days": 20, "annualization": 365},
        {"kline": ("open", "high", "low", "close")},
        "Estimates drift-independent volatility from intrabar OHLC movements.",
    ),
    "return_skewness": FactorMetadata(
        "skew(return,60)",
        {"lookback_days": 60},
        {"kline": ("close",)},
        "Measures asymmetry in the recent return distribution.",
    ),
    "return_kurtosis": FactorMetadata(
        "kurtosis(return,60)",
        {"lookback_days": 60},
        {"kline": ("close",)},
        "Measures tail heaviness in the recent return distribution.",
    ),
    "range_realized_vol_ratio": FactorMetadata(
        "mean((high-low)/close,20) / (std(return,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close")},
        "Compares intrabar range volatility with close-to-close realized volatility.",
    ),
    "volatility_regime_ratio": FactorMetadata(
        "std(return,20) / (std(return,60) + epsilon)",
        {"short_window_days": 20, "long_window_days": 60, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures whether short-term volatility is elevated relative to its longer regime.",
    ),
    "volume_momentum": FactorMetadata(
        "volume_t / volume_{t-20} - 1",
        {"lookback_days": 20},
        {"kline": ("volume",)},
        "Measures medium-horizon growth or contraction in trading activity.",
    ),
    "volume_regime_ratio": FactorMetadata(
        "mean(volume,20) / (mean(volume,60) + epsilon)",
        {"short_window_days": 20, "long_window_days": 60, "epsilon": 1e-12},
        {"kline": ("volume",)},
        "Measures recent activity relative to its longer-term volume regime.",
    ),
    "volume_shock": FactorMetadata(
        "volume_t / median(volume,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("volume",)},
        "Measures unusual current activity relative to a robust rolling baseline.",
    ),
    "obv_momentum": FactorMetadata(
        "(OBV_t - OBV_{t-20}) / sum(volume,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures directional on-balance-volume change normalized by recent activity.",
    ),
    "accumulation_distribution": FactorMetadata(
        "sum(close_location_imbalance*volume,20) / sum(volume,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close", "volume")},
        "Measures volume-confirmed accumulation or distribution pressure.",
    ),
    "money_flow_index": FactorMetadata(
        "100 - 100 / (1 + positive_money_flow_14 / negative_money_flow_14)",
        {"lookback_days": 14, "epsilon": 1e-12},
        {"kline": ("high", "low", "close", "volume")},
        "Measures buying and selling pressure using typical price and volume.",
    ),
    "vwap_deviation": FactorMetadata(
        "close_t / VWAP_20 - 1",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close", "volume")},
        "Measures price deviation from the recent volume-weighted average price.",
    ),
    "volume_weighted_return": FactorMetadata(
        "sum(return*volume,20) / (sum(volume,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures recent returns weighted toward periods with greater activity.",
    ),
    "body_to_range": FactorMetadata(
        "mean(abs(close-open)/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close")},
        "Measures the average share of each bar range occupied by the candle body.",
    ),
    "upper_wick_ratio": FactorMetadata(
        "mean(upper_wick/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close")},
        "Measures repeated rejection from intrabar highs.",
    ),
    "lower_wick_ratio": FactorMetadata(
        "mean(lower_wick/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("open", "high", "low", "close")},
        "Measures repeated rejection from intrabar lows.",
    ),
    "candle_efficiency": FactorMetadata(
        "abs(close_t-close_{t-20}) / sum(high-low,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close")},
        "Measures net price displacement relative to cumulative intrabar movement.",
    ),
    "range_expansion": FactorMetadata(
        "current_range / mean(range,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close")},
        "Measures whether the current bar range is unusually expanded.",
    ),
    "candle_body_direction": FactorMetadata(
        "mean(sign(close-open),20)",
        {"lookback_days": 20},
        {"kline": ("open", "close")},
        "Measures the recent balance of bullish and bearish candle bodies.",
    ),
    "close_location_dispersion": FactorMetadata(
        "std((close-low)/(high-low),20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Measures instability in where closes occur within their bar ranges.",
    ),
    "range_weighted_return": FactorMetadata(
        "sum(return*range_ratio,20) / (sum(range_ratio,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("high", "low", "close")},
        "Measures returns weighted toward periods with larger intrabar ranges.",
    ),
    "crypto_weekend_return": FactorMetadata(
        "mean(weekend_return,20)",
        {"lookback_days": 20},
        {"kline": ("timestamp", "close")},
        "Measures return behavior specifically during weekend observations in the 24/7 market.",
    ),
    "crypto_weekend_weekday_volume_ratio": FactorMetadata(
        "mean(weekend_volume,20) / (mean(weekday_volume,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("timestamp", "volume")},
        "Measures weekend activity relative to weekday activity.",
    ),
    "crypto_downside_volume_share": FactorMetadata(
        "sum(volume where return<0,20) / (sum(volume,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures the share of trading activity associated with negative returns.",
    ),
    "crypto_upside_volume_share": FactorMetadata(
        "sum(volume where return>0,20) / (sum(volume,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures the share of trading activity associated with positive returns.",
    ),
    "crypto_return_autocorrelation": FactorMetadata(
        "corr(return_t,return_{t-1},20)",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures short-horizon persistence or reversal in crypto returns.",
    ),
    "crypto_jump_intensity": FactorMetadata(
        "mean(abs(return)>mean(abs(return),20)+2*std(abs(return),20),60)",
        {"lookback_days": 60, "threshold_window_days": 20},
        {"kline": ("close",)},
        "Measures the recent frequency of unusually large absolute returns.",
    ),
    "crypto_volume_concentration": FactorMetadata(
        "sum((volume/sum(volume,20))^2,20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("volume",)},
        "Measures whether recent activity is concentrated in a small number of bars.",
    ),
    "crypto_price_range_volume_corr": FactorMetadata(
        "corr((high-low)/close,delta(log(volume)),20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close", "volume")},
        "Measures whether changes in activity coincide with expanding intrabar ranges.",
    ),
    "momentum_vol_adjusted": FactorMetadata(
        "return_20 / (std(return,20) * sqrt(20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures momentum after scaling by recent realized return risk.",
    ),
    "trend_tstat": FactorMetadata(
        "mean(return,20) / (std(return,20) / sqrt(20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures the statistical strength of the recent return direction.",
    ),
    "upside_downside_vol_ratio": FactorMetadata(
        "sqrt(mean(max(return,0)^2,20)) / (sqrt(mean(min(return,0)^2,20)) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Compares upside and downside semivolatility.",
    ),
    "realized_vol_change": FactorMetadata(
        "realized_vol_t / realized_vol_{t-20} - 1",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures acceleration or contraction in realized volatility.",
    ),
    "return_tail_to_median_ratio": FactorMetadata(
        "quantile(abs(return),0.95,60) / (median(abs(return),60) + epsilon)",
        {"lookback_days": 60, "quantile": 0.95, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures the heaviness of the recent absolute-return tail.",
    ),
    "dollar_volume_momentum": FactorMetadata(
        "close_t*volume_t / (close_{t-20}*volume_{t-20}) - 1",
        {"lookback_days": 20},
        {"kline": ("close", "volume")},
        "Measures medium-horizon growth in traded dollar volume.",
    ),
    "liquidity_regime_ratio": FactorMetadata(
        "mean(close*volume,20) / (mean(close*volume,60) + epsilon)",
        {"short_window_days": 20, "long_window_days": 60, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures current liquidity regime relative to its longer baseline.",
    ),
    "amihud_illiquidity_change": FactorMetadata(
        "illiq_20 / (illiq_{t-20} + epsilon) - 1",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures whether price impact per traded dollar is worsening or improving.",
    ),
    "turnover_volatility": FactorMetadata(
        "std(volume/close,20) / (mean(volume/close,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close", "volume")},
        "Measures instability in the volume-to-price turnover proxy.",
    ),
    "wick_asymmetry": FactorMetadata(
        "mean((upper_wick-lower_wick)/(upper_wick+lower_wick+epsilon),20)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("open", "high", "low", "close")},
        "Measures whether recent candles reject highs or lows more strongly.",
    ),
    "range_autocorrelation": FactorMetadata(
        "corr(range_ratio_t,range_ratio_{t-1},20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Measures persistence of intrabar range conditions.",
    ),
    "close_location_surprise": FactorMetadata(
        "close_location_t - mean(close_location,20)",
        {"lookback_days": 20},
        {"kline": ("high", "low", "close")},
        "Measures whether the current close is unusually high or low within its bar.",
    ),
    "candle_direction_autocorrelation": FactorMetadata(
        "corr(sign(close-open)_t,sign(close-open)_{t-1},20)",
        {"lookback_days": 20},
        {"kline": ("open", "close")},
        "Measures persistence in bullish or bearish candle direction.",
    ),
    "cross_asset_relative_momentum": FactorMetadata(
        "return(first_asset,20) - return(second_asset,20)",
        {"lookback_days": 20},
        {"kline": ("close",)},
        "Measures relative momentum between the ordered asset pair.",
    ),
    "cross_asset_correlation": FactorMetadata(
        "corr(return_first,return_second,30)",
        {"lookback_days": 30},
        {"kline": ("close",)},
        "Measures rolling co-movement between the ordered asset pair.",
    ),
    "cross_asset_beta": FactorMetadata(
        "cov(return_first,return_second,30) / (var(return_second,30) + epsilon)",
        {"lookback_days": 30, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures the first asset's rolling sensitivity to the second asset.",
    ),
    "cross_asset_volatility_ratio": FactorMetadata(
        "std(return_first,20) / (std(return_second,20) + epsilon)",
        {"lookback_days": 20, "epsilon": 1e-12},
        {"kline": ("close",)},
        "Measures relative realized volatility within the ordered asset pair.",
    ),
    "basis_funding_divergence": FactorMetadata(
        "basis_pct - mean(annualized_funding,30)",
        {"lookback_days": 30},
        {"basis": ("basis_pct",), "funding_rate": ("funding_rate",)},
        "Provides a carry-curve divergence proxy using daily basis and funding.",
    ),
    "basis_funding_divergence_zscore": FactorMetadata(
        "(divergence - mean(divergence,60)) / (std(divergence,60) + epsilon)",
        {"lookback_days": 60, "epsilon": 1e-12},
        {"basis": ("basis_pct",), "funding_rate": ("funding_rate",)},
        "Standardizes the basis-funding carry divergence proxy.",
    ),
}
